backend:
  name: git-gateway
  branch: main
  login: true
  roles: ["admin", "editor"]

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Projects"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      # - {
      #     label: "Author",
      #     name: "author",
      #     widget: "relation",
      #     collection: "authors",
      #     value_field: "username",
      #     search_fields: ["title", "username"],
      #     display_fields: ["title"]
      #   }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "_authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Display Name", name: "title", widget: "string" }
      - { label: "Username", name: "username", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }